### ISSUE TITLE
how to collect camera info from motioneye database

### ISSUE THREAD

**Issue by profileman00** [ccrisan/motioneyeos#2465] opened 2020-07-12 21:42 UTC
hello i am running motioneye 0.42.1 in ubuntu server 18. i want to configure sms notification to send personalized sms with the information of the camera that triggered the alert like in email notification and for that i need to know if it is possible to collect any useful info from the motioneye database like the **camera name**, **time**, and **date** using the _RUN A COMMAND_ to start a python script to collect the data required to personalize the sms before sending. 

if it is possible to get the required data above, how do i get to the database manager. like how do i access the database to query the data

**Comment by starbasessd** [comment] 2020-10-23 21:53
Closing, no comments/requests/followup after 60 days
If the issue is still not resolved, feel free to re-open or open a new case.

**Closed as completed by starbasessd** 2020-10-23 21:53 UTC
Labels: motioneye
