### ISSUE TITLE
log2ram

### ISSUE THREAD

**Issue by ghost** [ccrisan/motioneyeos#2456] opened 2020-07-05 14:46 UTC
Hello all,

i wanted to know if motioneyeos is using https://github.com/azlux/log2ram to not writing on the SD card all the time .

Thanks for your work.

**Comment by jasaw** [comment] 2020-07-09 01:36
motioneyeos is logging to SD card. There's currently no way to configure it to log to RAM. Ask @ccrisan whether there's any plan to make logging to RAM configurable.
There's also no need to use log2ram program to actually log to RAM.

**Comment by starbasessd** [comment] 2020-10-23 22:02
Closing, no comments/requests/followup after 60 days
If the issue is still not resolved, feel free to re-open or open a new case.

**Closed as completed by starbasessd** 2020-10-23 22:02 UTC
Labels: enhancement
