### ISSUE TITLE
Working schedule - add more intervals

### ISSUE THREAD

**Issue by thomsundberg** [ccrisan/motioneyeos#1319] opened 2018-01-06 17:49 UTC
Hi,
Thanks for this great piece of surveillance system.

Is there a possible to add two or intervals to the working schedule? That would be awesome.

**Comment by ccrisan** [comment] 2018-01-07 21:06
Unfortunately not.

**Comment by jasaw** [comment] 2018-01-14 16:21
This is a duplicate of https://github.com/ccrisan/motioneyeos/issues/70

**Closed by jasaw** 2018-01-14 16:21 UTC
Labels: duplicate
