### ISSUE TITLE
SSID unicode support

### ISSUE THREAD

**Issue by dreallday** [ccrisan/motioneyeos#1342] opened 2018-01-24 17:32 UTC
I'm attempting to connect to a network that is an emoji ssid for example: 📲

Has anyone had any luck with this? I've been getting 500s back on every attempt to try to set the ssid.

**Comment by jasaw** [comment] 2018-01-24 23:41
Duplicate of https://github.com/ccrisan/motioneyeos/issues/1114.

**Closed by jasaw** 2018-01-24 23:41 UTC
Labels: duplicate
