### ISSUE TITLE
BLUETOOTH

### ISSUE THREAD

**Issue by huvarda** [ccrisan/motioneyeos#1246] opened 2017-11-19 04:29 UTC
HOW CAN I USE BLUETOOTH WITH MOTIONEYEOS

**Comment by Chiny91** [comment] 2017-11-19 11:03
I see this is your second request but really you will have to give a little more.   What are you trying to achieve ?   What hardware are you using ?

I haven't looked through the motionEyeOS code to check but commonly you have to set a flag somewhere to enable bluetooth.   Not all boards supported by motionEyeOS have bluetooth built in.   So, my R Pi 3s don't have anything in /etc/bluetooth; have you looked there ?

**Comment by jasaw** [comment] 2017-11-19 12:28
This is a duplicate of #1231, and possibly duplicate of #1083, all created by @huvarda. Please do not spam. If you don't get a response for your issue, it means all motionEyeOS developers are busy. I'm not familiar with Bluetooth on motionEyeOS, so I can't answer your question. Hopefully someone else can answer your question.

**Closed by jasaw** 2017-11-19 12:28 UTC
Labels: duplicate, question

**Comment by huvarda** [comment] 2017-11-20 04:27
Sorry for spam, I just really wanted an answer.
