### ISSUE TITLE
wifi configuration lost after SSD filled up, had to reflash

### ISSUE THREAD

**Issue by takaforo** [ccrisan/motioneyeos#1556] opened 2018-06-19 07:42 UTC
Left the thing capturing until it ran of space.
Turned off, turned on wifi wouldn't connect because lack of space.
Connect ethernet cable and it boots ok.
Restart and it won't bother with wifi at all, even though I erased image files and plenty of space available.
Had to reflash with wifi config file for it to work again.

### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: (insert your version here, e.g. 20180314).

motionEye Version | 0.39.1
Motion Version | 4.1.1
OS Version | motionEyeOS 20180602

### Board Model

Raspberry Pi 3

### Camera

Raspberry Pi camera

### Network Connection

Wifi

### Peripherals

None

### Log Files

None

**Comment by jasaw** [comment] 2018-06-20 00:27
Duplicate of https://github.com/ccrisan/motioneyeos/issues/1164

**Closed by jasaw** 2018-06-20 00:27 UTC
Labels: duplicate
