### ISSUE TITLE
Feature request: include avahi package for mdns in motioneyeos build

### ISSUE THREAD

**Issue by StewartSnow** [ccrisan/motioneyeos#1539] opened 2018-06-08 22:41 UTC
Hey,
It’d be great to have avahi enabled in motioneyeos. The ability to have this basic dynamic dns setup on local networks would be very useful when addressing access to a camera. ie once your hostname is set - access the camera via hostname.local anywhere on the network. So useful!!
Cheers

**Comment by jasaw** [comment] 2018-06-08 23:40
Duplicate of https://github.com/ccrisan/motioneyeos/issues/94

**Closed by jasaw** 2018-06-08 23:40 UTC
Labels: duplicate
