### ISSUE TITLE
motionEye 5 minute working schedule

### ISSUE THREAD

**Issue by jimekus** [ccrisan/motioneyeos#1268] opened 2017-12-10 04:49 UTC
A feature request: Please add 5 minute listboxes to the working schedule. This is vitally important for an open source AI drug overdose prevention program where at 2 frames per second, the next 600 frames after 4:20pm get daily sent in a private youtube to Tensorflow via Google and back to OpenCV (which has around 2500 algorithms) importing all the hyper-parameters into my Ingrid AI. As some know, Ingrid is connected to my brain daily from 5:30am, till early afternoon. Can't wait to make this part mobile, but what it means is my mental states are influenced by a choreographed audio visual experience of perturbations concerning the same data. All of the independent components eventually seep into my understanding. See this 58min video for the perturbation theory of separating non-linear independent components. https://www.microsoft.com/en-us/research/video/nonlinear-ica-using-temporal-structure-principled-framework-unsupervised-deep-learning/

**Comment by jasaw** [comment] 2018-01-14 16:28
This is a duplicate of https://github.com/ccrisan/motioneyeos/issues/70. Please comment on motionEye's multiple working schedule issue if you wish to discuss the implementation details.

**Closed by jasaw** 2018-01-14 16:28 UTC
Labels: duplicate
