### ISSUE TITLE
date format DD/MM/YYYY but movie folders not in right order

### ISSUE THREAD

**Issue by SivanDuijn** [ccrisan/motioneyeos#2449] opened 2020-07-01 13:52 UTC
I've set my movies storage file names to be [%d-%m-%Y/%H-%M-%S], that works wonderfully.
But when opening the recorded movies window, it doesn't open the folder for this day by default
![afbeelding](https://user-images.githubusercontent.com/32020138/86251080-b34d1400-bbb1-11ea-9b57-c82df3022e64.png)

I'd like it to open the 01-07-2020 folder.
Ofcourse this is happening because 30 is bigger than 01 but could there be a solution for this?

motionEye Version: 0.42.1
Motion Version:      4.2.2+gitUNKNOWN
OS Version:             motionEyeOS 20200606

**Comment by starbasessd** [comment] 2020-07-01 14:07
I use: [%Y/%m%d/%H-%M-%S] sorts it into folder: Year, folder month, folder
day H:M:S.

**Comment by starbasessd** [comment] 2020-10-23 22:10
Closing, no comments/requests/followup after 60 days
If the issue is still not resolved, feel free to re-open or open a new case.

**Closed as completed by starbasessd** 2020-10-23 22:10 UTC
