### ISSUE TITLE
wpa_supplicant extended config

### ISSUE THREAD

**Issue by tinwhisker** [ccrisan/motioneyeos#776] opened 2017-02-19 16:00 UTC
I have a suggestion for the WiFi config - could you extend the choices beyond just SSID and PSK?
Or just add the extra proto/pairwise/group/key_mgmt defaults for WPA/WPA2 usage.
I don't know if ommiting them makes it WEP (really?) compatible, but if so, a checkbox/dropdown can give the option.

Example:
Tested with two unrelated USB WiFi dongles (MT7601U and  RT2870 compatible).
Both were found by MotionEyeOS, even sometimes would be 'pingable' by the static IP with the ARP showing the correct MAC.
The dongle would disconnect and (the RasPi) only became available by the eth port.

Carefully chosen SSID and PSK (no funny chars) didn't help.

When checking generic wpa_suppliment guides, they seemed to specify extra info.

Going from:

network={
    ssid="MySSID"
    scan_ssid=1
    psk=myPSK
}

to

network={
    ssid="MySSID"
    scan_ssid=1
    proto=WPA RSN
    key_mgmt=NONE
    pairwise=CCMP TKIP
    group=CCMP TKIP
    psk=myPSK
}

Interestingly, I set key_mgmt to 'WPA-PSK' but that got replaced with 'NONE'.
This may be because my PSK was obfuscated by wpa_passphrase - which is not included in MotionEyeOS.
You probably can use the clear-text string and set key_mgmt=WPA-PSK, but I didn't test further as after I fixed my setup, I installed the camera & pi before it got dark out.

**Comment by ccrisan** [comment] 2017-02-20 08:19
Hmm, let's take the problems here one by one.

1. Are you able to reproduce the `key_mgmt` replaced with `NONE`? If yes, what are the steps? Normally, motionEyeOS should leave it to whatever it is set.
2. Did your problem get fixed by adding the `pairwise`, `group` or `proto`? Or was it just about `key_mgmt`?

**Comment by bortek** [comment] 2017-06-01 11:03
Closing this issue due to interest. If still interested please post your question in the forum page.

**Closed by bortek** 2017-06-01 11:03 UTC
