### ISSUE TITLE
Restore configuration failed

### ISSUE THREAD

**Issue by Priso19** [ccrisan/motioneyeos#190] opened 2016-03-03 19:33 UTC
Hi, after putting some accents (é, à, è) in a Prowl web URL Hook  my eyemotion server crash:
it says "recommended refresh"

After the refresh, my four camera disappeared (they were not "Fast camera").

So I wanted to backup my configuration on a new image disk, message from motion eye : 
"Failed to restore the configuration!"

What have I doing wrong ? 
Sorry but I have no log file because I reset my SD card...

Config :
_Mac OS 10.7.5 on a MacBook dual USB
Safari 6.1.6
motioneye on a ethernet Raspberry Pi 2 with no camera on it
Current Version : 20160221_

**Comment by ccrisan** [comment] 2016-03-04 21:00
Please never attach files that contain sensitive data. I have removed your attachment now, I have it on my laptop and I'll try to reproduce the problem.

**Comment by pumbaa2183** [comment] 2016-03-05 18:59
I have had a similar issue after trying to restore a backup
motioneye on a wifi connection Raspberry Pi 2 with one camera
Current Version : 20160221
MacBook Pro  OSX 10.11.2
Safari 9.1

**Comment by ccrisan** [comment] 2016-03-06 08:56
@Priso19 I cannot seem to reproduce your problem. However the file you have attached (which I have removed due to sensitive data) is a .zip archive that contains a "motioneye-config" folder and __MACOSX folder. It doesn't look like a configuration backup file created by motionEyeOS (which is a .tar.gz file with all the files in the root of the archive).

**Comment by ccrisan** [comment] 2016-03-06 08:56
@pumbaa2183 what are the exact steps that you follow when you get this error? Please walk me through it.

**Comment by Priso19** [comment] 2016-03-06 09:20
First, thank you for your attention about my sensitive data.

 Indeed I had opened the archive file to view its contents, sorry.

For me, on MAc OS 10.7.5 (Lion) and Safari 6.1.6, the backup button generate a .tar file not .tar.gz
Perhaps Mac OS X automatically decompresses the file after the download?

**Comment by Priso19** [comment] 2016-03-06 09:32
I found the backup file .tar.gz in the trash !
Renamed more with a number incremented according to the number of existing file :
"motioneye-config.tar 10-23-45-020.gz"

I took it out of the trash and then remove the unnecessary character and it works correctly.

![restor_ok](https://cloud.githubusercontent.com/assets/17503388/13553349/8db7e1aa-e386-11e5-9a3b-c21945db97a8.png)

**Comment by ccrisan** [comment] 2016-03-06 09:41
Alright, I'll close the issue then.

**Closed by ccrisan** 2016-03-06 09:41 UTC

**Comment by Priso19** [comment] 2016-03-06 09:57
The simple solution would be to request a name for the backup file and check if there is already one with the same name on the disk to delete it before saving.

Because Mac OX anyway unpack the archive (first level) and renames himself the existing file without asking his replacement :

"motioneye-config.tar"
"motioneye-config-1.tar"
"motioneye-config-2.tar"

Thank you for your time Calin.

**Comment by pumbaa2183** [comment] 2016-03-06 16:01
Clicked backup in the web UI and saved a back up file — for some reason its saving it as an .img.gz and not a tar.gz ( see screen 
shot) 

I am running the latest version of Motioned OS using MacBook Pro 10.11.4 and safari 9.1

**Comment by ccrisan** [comment] 2016-03-06 16:08
Please attach the screenshot.

**Comment by pumbaa2183** [comment] 2016-03-06 16:12
sorry about that -- apparently the screen shot I sent from email didn't post :( 
Update : I did just create a new back up by clicking back up and it is saving it as a config.tar file 
![screen shot 2016-03-06 at 11 12 09 am](https://cloud.githubusercontent.com/assets/17677233/13555351/506617e4-e38c-11e5-9f4f-3437fa234fce.png)


![screen shot 2016-03-06 at 10 55 37 am](https://cloud.githubusercontent.com/assets/17677233/13555344/250fa4fc-e38c-11e5-9168-269f2af52f5b.png)

**Comment by Priso19** [comment] 2016-03-06 16:22
What is the size of the img file? Are you sure it's not the motioneyeos archive? Not the backup file ?

**Comment by pumbaa2183** [comment] 2016-03-06 18:33
My Bad the .img.gz is 230mb that must be the archive the .tar is 41 kb

**Comment by Chiny91** [comment] 2017-05-30 17:51
I know this is an old issue but it could do with a tidy conclusion; it would have helped me anyway 😄    For those using macOS/Safari, Safari (rather than macOS) by default partly unpacks the backup archive making it unusable to motionEyeOS.

A workaround is to change the Safari default:
Safari->Preferences->General 
Uncheck _Open "safe" files after downloading_

**Comment by jordipalet** [comment] 2019-06-07 08:58
Hi,

I did a backup of my configuration (5 cameras), and saved it correctly.

Upgraded with pip install motioneye --upgrade and the cameras are gone.

I restored the backup and restarted and still say no cameras defined ...

even if I restore manually the contents of /etc/motioneye, it looks like not recognizing the config files.

Any hints?

**Comment by Numline1** [comment] 2021-12-30 16:50
Just to add to this, if you end up in a situation where Safari decides to unpack the file, leaving you confused with your `.tar` archive in `Downloads` folder, the original file (`.tar.gz`) will be in your Trash, so you can just restore it and import it into MotionEye.
