### ISSUE TITLE
20180401 prerelease

### ISSUE THREAD

**Issue by Banditen01** [ccrisan/motioneyeos#1501] opened 2018-04-27 22:24 UTC
Have been running same configuration for a couple of years now but after latest prerelease I lost connection with my cameras, tried to add cameras again then it worked for a short while and same problem again?
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/1956875/motioneye.log)
[boot.log](https://github.com/ccrisan/motioneyeos/files/1956876/boot.log)

### motionEyeOS Version

I am running motionEyeOS version: 20180401 prerelease

### Board Model

I am using the following board/model: PI 2b

### Camera

I am using the following type of camera: Onvif CN noname (rtsp stream), Yi (rtsp stream)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)

**Comment by ccrisan** [comment] 2018-04-28 19:39
This certainly sounds like a network issue.

**Comment by cedrik9** [comment] 2018-05-03 10:45
Hello, have same Problem.
I went back to last release and all is ok

**Comment by Banditen01** [comment] 2018-05-03 10:50
@cedrik9 Tx then I know it's not my fault, haven't changed anything just made an update, my system has been running without problems for like I said 2 years therefore it hard to accept it's a network issue.

**Comment by ccrisan** [comment] 2018-05-03 10:52
Guys is this problem fully reproducible or does it only happen every now and then?
Can you please attach your motion.log files?

**Comment by Banditen01** [comment] 2018-05-03 11:16
If i start/restart the problem exists directly (all the time), if I add and delete a camera like in the video I have attached earlier it works for while and then same problem again.
[motion.log](https://github.com/ccrisan/motioneyeos/files/1970585/motion.log)

**Comment by cedrik9** [comment] 2018-05-03 12:47
I can't host the motion.log because i went back , but it is possible that it is a network problem, but on the motioneyeos software. all network cameras have no funktion and the connection to the nas also is not working, but access via browser is running. 
My motion.log looks like that in the first post from banditen01

**Comment by ccrisan** [comment] 2018-05-03 21:00
@Banditen01 @cedrik9 could you guys by any chance try running your setup with [motion 4.1.1](https://github.com/Motion-Project/motion/releases/tag/release-4.1.1) on [Raspbian with motionEye](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian) and the exact setup (adding your RTSP cameras)?

**Comment by Banditen01** [comment] 2018-05-04 21:46
Have done the test now, exact same problem as before, UI searching for the cameras with no result but if I ad and deltet a camera it works for a short while.

**Comment by Banditen01** [comment] 2018-05-15 03:34
@ccrisan have tried to figure out how to port forward the rtsp stream thru my router but haven’t managed to make it work.

**Comment by cedrik9** [comment] 2018-06-11 07:51
Hello,
i spend a few time to test the new prerelease motionEyeOS 20180602.

the upper written problems come with configuring the nas. i have a fritzbox with harddisk. every time before i use the network storage to save the triggered files, and up to the last full release it works. 
if i now try to use the nas, with same settings, no camera work and no nas connection is possible .
if i use ftp, all camera works.
greeting karsten

**Comment by ccrisan** [comment] 2018-06-11 10:37
@cedrik9 please attach your motioneye.log and messages.log files.

**Comment by cedrik9** [comment] 2018-06-11 12:57
Sorry i didn't have. I went back to last release . Rolleye.
If i have a little bit time i try it again. latest at next release

**Comment by cedrik9** [comment] 2018-06-11 14:19
Hello again. found an old copied out part like this from dmesg.log
[Thu Jan  1 03:50:55 1970] No dialect specified on mount. Default has changed to a more secure dialect, SMB2.1 or later (e.g. SMB3), from CIFS (SMB1). To use the less secure SMB1 dialect to access old servers which do not support SMB3 (or SMB2.1) specify vers=1.0 on mount.
[Thu Jan  1 03:50:56 1970] CIFS VFS: cifs_mount failed w/return code = -112

.... 16:12:18: [motioneye]    ERROR: failed to mount smb share "//192.168.178.1/fritz-nas/FUJITSU-MJA2500BHG2-01" at "/data/media/motioneye_192_168_178_1_fritz_nas_fujitsu_mja2500bhg2_01_admin"
.... 16:12:18: [motioneye]    ERROR: access to network share //192.168.178.1/fritz-nas/FUJITSU-MJA2500BHG2-01 failed: cannot mount network share

**Comment by ccrisan** [comment] 2018-06-11 20:57
@cedrik9 this is rather interesting. Things have changed a bit and I'll need to revise the way we mount the SMB network drive. Any ideas are welcomed :)

**Comment by cedrik9** [comment] 2018-06-12 06:12
@ccrisan 
Hello,
in my opinion it is very easy.
The error message tell you what you have to do.
At that point where you mount the external smb, you have to add cifs -o vers=1.0 as option.
Not all NAS / Routers support smb/cifs > 1.0 so it would be nice if you can make a check box to use vers 1.0 or the given now (e.g. 2 or 3).

some hints maybe here
https://github.com/blinkreaction/boot2docker-vagrant/issues/66.
AVM , producer of Fritzbox tell you only to use ftp as workaround, so they have no updates planned.
Its like eat or die 👎 .
greeting karsten

**Comment by cedrik9** [comment] 2018-06-12 07:06
Think must be added vers=1.0  in motioneye smbctl.py   _mount included in actual ops for fast test
kr karsten

**Comment by cedrik9** [comment] 2018-06-20 10:51
Any news?

**Comment by ccrisan** [comment] 2018-06-24 13:36
https://github.com/ccrisan/motioneye/commit/1bce4dd358774f69e52fa3814eeea54e9fc6b156 should fix this issue. It will be part of the next motionEyeOS release.

**Closed by ccrisan** 2018-06-24 13:36 UTC

**Comment by ccrisan** [comment] 2018-06-26 19:21
@Banditen01, @cedrik9 can you please try the latest [nightly dev build](https://github.com/ccrisan/motioneyeos/releases/tag/nightly-dev) and see if the problem has been fixed?

**Comment by cedrik9** [comment] 2018-06-27 07:57
Hello,
how can I update without new install with sdcard ?

**Comment by ccrisan** [comment] 2018-06-27 09:11
You could try the command `fwupdate upgrade nightly-dev`. I never tested upgrading to a nightly build but it should work.

**Comment by cedrik9** [comment] 2018-06-27 10:54
Hello @ccrisan ,
it works , top

**Comment by ccrisan** [comment] 2018-06-27 11:22
Then I'll make a stable release with what we have now.
