### ISSUE TITLE
invalid login credentials after setting up email notification

### ISSUE THREAD

**Issue by bruster999** [ccrisan/motioneyeos#1484] opened 2018-04-12 11:37 UTC
Hi,
I love this product. Thanks for making it public!

The problem I am reporting is that the login credentials change after setting up Working Schedule.
 
I am using a RasPi Zero W with the 20180224 version of motioneyeos. I am able to install the image, boot it up, log in as admin, find the web page and log in there and set up a web cam. I was able to set up motion detection and have email alerts sent when a motion event happens. This all worked fine until I turned on Working Schedule. After I applied the changes, the settings in Motion Notification were wiped out (all blank fields). After re-entering the same email address, smtp, port, etc. once I apply the settings I get logged out and can't get back in. This happened twice. After the first time I started with a new image but the exact same thing happened in the same order. Now when I enter admin with no pw I get "Invalid Credentials" at the web login prompt.

**Comment by ccrisan** [comment] 2018-04-12 14:08
Duplicate of #1317.

**Closed by ccrisan** 2018-04-12 14:08 UTC
