### ISSUE TITLE
temporarily stop motion detection?

### ISSUE THREAD

**Issue by x011** [ccrisan/motioneyeos#1018] opened 2017-07-03 21:57 UTC
Is there a way to temporarily stop motion detection, via ssh perhaps?
This would be useful when you're about to enter the place where the camera is operating and you don't want to trigger web-hooks, video and photo uploads.
Tks!

**Comment by jasaw** [comment] 2017-07-06 23:58
This should be supported once issue #842 is implemented.

**Comment by jasaw** [comment] 2017-07-31 02:54
Duplicate of issue #93 .

**Closed by jasaw** 2017-07-31 02:54 UTC
Labels: duplicate
