### ISSUE TITLE
SMTP Account password with single quote, makes motioneyeos to crash

### ISSUE THREAD

**Issue by pkspandiyan** [ccrisan/motioneyeos#2478] opened 2020-07-30 15:46 UTC
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20200606.

### Board Model

I am using the following board/model: Raspberry PI Zero W.

Thanks much to CCrisan and Open Source Community for building this awesome MotionEyeOS.

Noticed an issue while trying to configure motioneye OS to send email when motion is detected.
Issue is MotionEyeOS keep showing the message "An error occurred. Refreshing recommended".

After troubleshooting the issue, noticed that, its because of an special character in my SMTP account password.
Special character which caused the issue in my SMTP account password is single quote.
In /data/etc/camera-1.conf, for on_event_start configuration, SMTP account password is specified with in single quote.
Hence it causes issue. 

As an workaround edit this file  /data/etc/camera-1.conf to specify SMTP account password in double quote and it resolved the issue. 

However, when ever I need to modify some configuration through motioneyeos web UI, this issue happens and I have do the above mentioned workaround.

Also, I am going to change my password to avoid the need for repeating the workaround. 

Thought will report this issue here.

Regards,
pksp

**Comment by starbasessd** [comment] 2020-10-23 21:26
Closing, no comments/requests/followup after 60 days
If the issue is still not resolved, feel free to re-open or open a new case.

**Closed as completed** 2020-10-23 21:27 UTC
Labels: troubleshooting
