### ISSUE TITLE
Feature request: enable mpeg4 streaming for Fast Network Camera mode

### ISSUE THREAD

**Issue by d-faure** [ccrisan/motioneyeos#1266] opened 2017-12-08 16:03 UTC
Since the Raspberry's GPU is also able to produce a h264/mp4 stream on its own, this could be nice to have it available in the Fast Network Camera mode.

**Comment by jasaw** [comment] 2017-12-08 17:37
Duplicate of this issue: https://github.com/ccrisan/motioneyeos/issues/636

**Closed** 2017-12-08 17:38 UTC
Labels: duplicate
