### ISSUE TITLE
sound recording?

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#57] opened 2015-12-06 11:14 UTC
hi. is it possible to add audio sources? like usb sound card or some board have mic in. and assosiate it with video sources so record video with sound?

**Comment by ccrisan** [comment] 2015-12-06 11:14
No.

**Comment by shinji2009** [comment] 2015-12-06 11:16
thanks for answer. thats a bummer ( it will be realy useful ((

**Comment by mitchelldavis44** [comment] 2016-03-07 04:22
+1 on the sound issue.

**Comment by Mugiwara75** [comment] 2016-04-30 17:17
+1 for sound ;-)

**Comment by Mayday171** [comment] 2016-06-06 21:15
+1 mic support would be great

**Comment by spyrotsk** [comment] 2016-07-23 10:28
+1 for sound support!
Thanks! ;-)

**Comment by hellyberry** [comment] 2017-01-07 01:13
Sound and universal sensor action support would be great, for monitoring PIR, Temperature, Moisture, ...

**Comment by bortek** [comment] 2017-02-23 14:04
This is duplicate of #57

**Closed by bortek** 2017-02-23 14:04 UTC
Labels: duplicate

**Comment by shinji2009** [comment] 2017-02-23 14:13
it is #742 is duplicate of this request, it is 25 days old, mine is more than a year

**Comment by bortek** [comment] 2017-02-23 14:16
Does not matter really which Issue we will be driving since it is the same feature request. Lets keep #742 ac active and keep this one closed. Thanks!
