### ISSUE TITLE
Restart from UI Web Browser Causes MotionEye to never restart. Just boots root.

### ISSUE THREAD

**Issue by OgityBogityBoo** [ccrisan/motioneyeos#963] opened 2017-05-24 00:47 UTC
Hello,

I am running the latest version of MotionEye OS on the Raspberry Pi 3 Model B.
I have followed the installation steps as outlined and I am able to get MotionEye running.
I am able to reboot it, turn the raspberry pi off and on and I am still able to get MotionEye to run.

My only problem is that when I log into the IP Address associated with the pi, and I make a change, such as changing the admin password, the UI says it will cause the system to restart.
After I hit okay is where my problems begin.

Raspberry Pi will restart but it will not load MotionEye OS again. It gets to this screen (see attached screenshot).

Normally it would say Starting MotionEye OS. But here it simply asks for the root logon and that's it. MotionEye is never started.

How do I start it up again? I am not specially fluent in Linux so I might be missing something obvious.

After logging into the root I try:
meyectl startserver and it claims it doesn't exist, even though if I just type "meyectl" it shows "startserver" as an option.
![img_1842](https://cloud.githubusercontent.com/assets/28911317/26382234/258d16b2-3fe8-11e7-977d-34e288b728bb.JPG)

Thank you for any help you can provide. I am not sure if this is an error on my end, error on hardware or software. It appears to funciton perfeclty until rebooting from the web browser interface.

**Comment by ccrisan** [comment] 2017-05-24 06:29
Is this fully reproducible? If yes, what are the exact steps you follow (changes you make) to get it into this state?

**Comment by bortek** [comment] 2017-06-01 11:51
Closing this issue due to interest. If still interested please post your question in the forum page.

**Closed by bortek** 2017-06-01 11:51 UTC
