### ISSUE TITLE
Choosing advanced settings causes password to no longer work

### ISSUE THREAD

**Issue by jennib** [ccrisan/motioneyeos#1103] opened 2017-08-27 18:51 UTC
I changed the password for admin account and all was good.  Rebooted and all is well.

Then I switched advanced options on and could no longer log in.

**Comment by ccrisan** [comment] 2017-08-27 18:56
What version, what board?

**Comment by jennib** [comment] 2017-08-27 19:04
Raspi 3 latest version

**Comment by jennib** [comment] 2017-08-27 19:05
motioneyeos-raspberrypi3-20170710.img

**Comment by ccrisan** [comment] 2017-08-27 19:14
Please try clearing your browser's cache. If that doesn't work, I'll need some more details (screenshots, errors, logs, something).

**Comment by jennib** [comment] 2017-08-27 19:38
I tried two different browsers.

The problem happened twice.  The first time I change both password and advanced slider.  The second I changed only password, then rebooted and was able to log in both the web page and ssh but then changed the advanced slider and could no longer log in.

Since I am in a rush I won’t be able to try again for a few days.

Cheers

**Comment by jennib** [comment] 2017-08-28 02:44
Just want to say thanks.  I'm using MotionEye on Raspbian stretch and it works great.

**Comment by jasaw** [comment] 2017-10-11 13:17
@jennib Is this still an issue for you?

**Comment by polkyb** [comment] 2017-10-15 00:30
Hi,

I'm getting this issue with motioneyeos-raspberrypi3-20171008

I can log in, change passwords etc. but when I go to advanced mode, change IP to static and reboot I can't get back in with the password that worked before the change.
Tried multiple browsers and cleared caches between attempts.

**Comment by RPiSpy** [comment] 2017-10-24 20:58
mmm this has just happened to me. I updated to the latest version, changed the network timeout setting from 40 to 60 and clicked "Apply". The system rebooted but now I can't login using "admin" and my password. I tried in MS Edge and Chrome.

**Comment by jasaw** [comment] 2017-10-24 23:17
@RPiSpy I think you've hit issue #1116.
Please clear your browser cache and refresh the page.
Try logging in using these passwords: `*****`, or the sha1 of the five stars: `133e3d6b775613651eaedbf7e609d244f2f852af`

**Comment by dernew** [comment] 2017-11-05 18:58
Same problem here after upgrading to 20171008 - system rebooted, tried multiple browsers/ machines, no access via browser or SSH, old password not accepted, nor, ***** or sha1 string nor serial number.  Clearing cache does not fix it.    its a Raspi2, it has been running various versions of Meye for over a year.  System still working for view access [i.e. no password] but I can't change anything or get at any logs.
I've read through #1116 and tried everything there.  Annoying problem.  System rock solid up to the upgrade... there is a lesson for me there !

**Comment by PieterGit** [comment] 2017-12-24 16:05
With upgrade motionEyeOS 20170710 to 20171008 I can confirm password has been changed to `*****` (5 times asterisk) when I changed an advanced setting (rpi3)

**Comment by ccrisan** [comment] 2017-12-27 00:03
@PieterGit this is a duplicate of #1116. The solution is to clear your browser's cache and resetting the password (if possible) after a refresh.

**Closed by ccrisan** 2017-12-27 00:03 UTC
