### ISSUE TITLE
Password Changed? after changing WiFi TimeZone

### ISSUE THREAD

**Issue by b0rnwr0ng** [ccrisan/motioneyeos#1169] opened 2017-10-09 03:45 UTC
Upgraded to 20171003, still having a WiFi drop out issue on pi3 on one device so far, so changed timezone to US/Eastern to America/NewYork and then I couldn't log back in at all.. had to do a new install..

**Comment by Apathialol** [comment] 2017-10-09 03:58
I updated to the new version and it locked me out too, no timezone change required.

**Comment by jasaw** [comment] 2017-10-09 05:15
I think this is a duplicate of issue #1116.
Please clear your browser cache and refresh the page.
Try logging in using these passwords: `*****`, or the sha1 of the five stars: `133e3d6b775613651eaedbf7e609d244f2f852af`

**Closed** 2017-10-14 14:57 UTC
Labels: duplicate
