### ISSUE TITLE
Feature request: user defined motion detection region

### ISSUE THREAD

**Issue by adriankwil** [ccrisan/motioneyeos#390] opened 2016-07-10 16:35 UTC
Would you be able to add a feature where you are able to select a region in which motion is detected? So that any amount of motion is allowed outside the region, but recording is only triggered inside the region? This would be a very useful feature! Or is this already an option?

**Comment by ccrisan** [comment] 2016-07-10 16:37
It's in the works.

**Comment by adriankwil** [comment] 2016-07-10 16:38
Fantastic! Thanks.

**Comment by fredericcollin** [comment] 2016-07-10 23:26
I approve 100%!

**Comment by timdonovanuk** [comment] 2017-06-07 10:09
Request for useful title ;)

This feature is implemented now.

**Comment by jasaw** [comment] 2017-08-24 01:58
Duplicate of issue #89.
Feature already implemented.

**Closed by jasaw** 2017-08-24 01:58 UTC
Labels: feature request
