### ISSUE TITLE
Motioneyeos and Raspberry Pi 4

### ISSUE THREAD

**Issue by bobster316** [ccrisan/motioneyeos#1980] opened 2019-07-04 20:36 UTC
Please advise when we can expect to get Motioneyeos working on a Raspberry Pi 4.
Thanks

**Comment by jasaw** [comment] 2019-07-04 23:55
Duplicate of https://github.com/ccrisan/motioneyeos/issues/1969

**Closed by jasaw** 2019-07-04 23:55 UTC
Labels: duplicate, question
