### ISSUE TITLE
Resolution Scale - 1080p

### ISSUE THREAD

**Issue by RichBuck89** [ccrisan/motioneyeos#2483] opened 2020-08-03 16:02 UTC
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING]

I confirm that I have read the [FAQ]

### motionEyeOS Version

I am running motionEyeOS version: 0.42.1

### Board Model
PI4 

### Camera

I am using the following type of camera: ( MMAL, Network Camera, .

My camera model is: (insert your camera model, e.g. Logitech C290).

MakerFocus Raspberry Pi4 Camera IR
https://www.amazon.com/gp/product/B07DPNDP6R/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
### Network Connection

My motionEyeOS unit is connected to the network via: (Ethernet).

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

POE Hat
### Log Files

Hello, 

I don't understand why the image doesn't scale on my Motioneye camera. When I use 1080p half of the image is cut off. When I use 1600 x 1200 I get the full view. 

1080P
![image](https://user-images.githubusercontent.com/58198648/89202453-92912900-d578-11ea-8dd3-419248e003e6.png)

1600 x 1200

![image](https://user-images.githubusercontent.com/58198648/89202524-b18fbb00-d578-11ea-9fcc-570c0e4632d7.png)

I'd perfer to use 1080p but it's cutting out 1/4 of the overall image. I've played around with the collumns and virtal fit frames. 

Is this a limitation on the camera that I purchased or an issue with MotioneyeOS?

**Comment by jasaw** [comment] 2020-08-03 23:49
I believe this is an issue with Raspberry Pi GPU firmware. I'm not sure what we can do about it. You could try raspivid to see if it behaves the same way. If it does, you could report the problem to the Raspberry Pi github project.

**Comment by starbasessd** [comment] 2020-10-23 21:20
Closing, no comments/requests/followup after 60 days
If the issue is still not resolved, feel free to re-open or open a new case.

**Closed as completed by starbasessd** 2020-10-23 21:20 UTC
