### ISSUE TITLE
Purple image with motioneeye

### ISSUE THREAD

**Issue by bend94** [ccrisan/motioneyeos#2477] opened 2020-07-29 09:19 UTC
hi
i installed two picam (one on pi3 and one on pi zerow)
i added the 2 into motioneye

my issue: the 2 images are purple
do you know why?
thx

**Comment by bend94** [comment] 2020-07-29 14:13
i did find something
add that line in /boot/config.txt 

awb_auto_is_greyworld=1

and reboot  it seems to fix

**Comment by JohanD78** [comment] 2020-07-30 18:01
If u have a cam that was labled No-IR then they are showing correct.

Check this link the "normal" pi camir and no-ir cam pics

https://raspi.tv/wp-content/uploads/2013/10/pinoir-thumbnail.jpg

**Comment by starbasessd** [comment] 2020-10-23 21:27
Closing, no comments/requests/followup after 60 days
If the issue is still not resolved, feel free to re-open or open a new case.

**Closed as completed by starbasessd** 2020-10-23 21:27 UTC
