### ISSUE TITLE
"During Working Schedule" vs. CCTV expectations

### ISSUE THREAD

**Issue by seanpsilverman** [ccrisan/motioneyeos#676] opened 2017-01-02 08:40 UTC
A lot of times I have found that motion detection stopped working, despite my having turned it on correctly and carefully chosen 1/2 compatible codecs...

If I follow the application of "Outside Working Schedule" up with an immediate reboot - having already put any other newly desired settings in place, than motion detection does tend to pick up again.

No matter what the circumstance, except for the moment between making my drop-down selection and hitting the apply button, the setting always appears as if set to "During working schedule" which is never ever what I want.

I have a strong preference for having the camera recording after hours, when robbers come to steal things, so I can't help but notice...

I know from the message boards here, and past configurations I have brainstormed, that humans do exist who make the same investment as myself setting up digital CCTV, but who then choose to turn it off automatically during certain periods of time regardless of any environmental factors that might be occurring.

At the end of day, I wouldn't ever not capture footage of potential crime/s after all the hard work is done.  

Many think just like me.

I ask you to consider making "always on" the new default operational norm given the availability requirements of the CCTV application.  The schedule folks are already committed to extra work (entering and maintaining the schedule, collaborating, and making sure it still has blind spots in place when you leave for holiday...).  If people see the equipment drawing power, and it was working fine 10 minutes ago, they are apt to assume it is working away on their behalf.

A compromise might be forcing the reboot onto the user, a la Microsoft, when they become positioned in a way that jeopardizes the success of their ongoing surveillance efforts.  

As it stands now, I would fear performing routine actions remotely, out of concern that I could unwittingly break the most critical feature of all.

Thanks for your consideration in regards to this matter.

**Comment by ccrisan** [comment] 2017-01-02 09:48
So what seems to be the problem? You choose "Outside Working Schedule" but it gets back to "During Working Schedule"? If yes, can you reproduce this?

**Comment by seanpsilverman** [comment] 2017-01-02 09:55
It always immediately returns to "During Working Schedule" immediately after I hit "Apply" if not sooner.

I tried, at one point, to have a schedule.  I didn't like having it be off for 1 minute per day, so I abandoned that.  If I can see the option at all, it always says "During Working Schedule."  Sometimes it is unfortunately the truth, other times it is merely a bad omen.

**Comment by ccrisan** [comment] 2017-01-02 10:10
Could you please send me your config files (motion.conf and thread-*.conf) after removing sensitive data from them? Also, before you hit apply, is there any other setting that you tweak?

**Comment by seanpsilverman** [comment] 2017-01-02 10:27
Files are scrubbed and attached.

Beforehand, yes I almost certainly logged in to test something.

Afterward I change that setting, apply it and seal the deal with a reboot.
I've learned not to do any of that out of order and when sticking to that I
generally come out fine.

-Sean

**Comment by seanpsilverman** [comment] 2017-01-02 10:29
If I could inject fake noise into my unmasked area to test without getting
up / driving somewhere that'd be a game changer.  I have never seen such a
feature before though...

**Comment by bortek** [comment] 2017-06-01 10:52
Closing this issue due to interest. If still interested please post your question in the forum page.

**Closed by bortek** 2017-06-01 10:52 UTC

**Comment by seanpsilverman** [comment] 2017-06-01 14:56
Hard to test since masking stopped working altogether...

Working schedules and masks are some of the major (basic) motivators for
upgrading from time lapse VCRs.  Without it there is not a viable product
no matter how smooth the interface.  I will have to try less glamorous
solutions.
