### ISSUE TITLE
Raspi Zero2 W with Full HD

### ISSUE THREAD

**Issue by orcadiver** [ccrisan/motioneyeos#2878] opened 2022-02-02 13:43 UTC
Hi all,
my two Raspi Zero2 W are working fine so far.
Only the two highest resolutions (from 1600x1200) cause the Raspi to freeze (it requires a reboot), the highest (1920x1080) even irreversibly and requires the import of a new image - at any framerate, but at higher framerates it happens faster.
Can this be due to the performance of the Raspi or is it just the configuration.

**Comment by starbasessd** [comment] 2022-02-02 13:52
I vote configuration. With the Read-Only file system, it'd be interesting to see if / what gets corrupted. There are known issues with motion & higher resolutions and frame rates, OMX, and so forth. It's possible you are getting into 'race' conditions (where events start piling up, overlapping, unable to complete the previous trigger, etc...) I would switch to a non-OMX file format (highest GPU usage), lower resolution, lower frame rate, Movie Passthrough for 'recording files' (but you lose text overlays and such)...

**Comment by starbasessd** [comment] 2022-02-02 13:57
Is it possible that the /data partition gets full?
SSH into the Pi and run 
df -h
and report
Is it possible its overheating or has a bad (low voltage) power supply?
SSH into the Pi and run 
vcgencmd get_trhottled
and report

**Comment by orcadiver** [comment] 2022-02-02 14:14
a) it occurs (also) without motion detection
b) the 128GB SDCard is virtually empty

**Comment by starbasessd** [comment] 2022-02-02 14:19
Is it possible its overheating or has a bad (low voltage) power supply?
SSH into the Pi and run
vcgencmd get_throttled
and report

**Comment by orcadiver** [comment] 2022-02-02 14:19
login as: admin
Pre-authentication banner message from server:
| Welcome to motionEye-Cam1!
End of banner message from server
admin@192.168.11.41's password:
[root@motionEye-Cam1 ~]# vcgencmd get_trhottled
error=1 error_msg="Command not registered"
Use 'vcgencmd commands' to get a list of commands
[root@motionEye-Cam1 ~]#

**Comment by starbasessd** [comment] 2022-02-02 14:20
Yeah, typo... Corrected...
vcgencmd get_throttled

**Comment by orcadiver** [comment] 2022-02-02 14:21
[root@motionEye-Cam1 ~]# vcgencmd get_throttled
throttled=0x0
[root@motionEye-Cam1 ~]#

**Comment by starbasessd** [comment] 2022-02-02 14:22
Try when it's frozen...

**Comment by orcadiver** [comment] 2022-02-02 14:29
just now the Raspi held for several seconds with 20 frames 1920x1080 (result of "vcgencmd get_throttled" continuously "throttled=0x0", then I switched to 25 frames and it froze (via SSH no reaction anymore)
then set to 20 frames again, it returns a video image again and result of "vcgencmd get_throttled" unchanged "throttled=0x0"

**Comment by starbasessd** [comment] 2022-02-02 14:35
Interesting. Thoughts, @jawsper ?

**Comment by orcadiver** [comment] 2022-02-02 14:40
now it has been running for over a minute even at 1920x1080 and 30 frames, and gives the following message:
[root@motionEye-Cam1 ~]# vcgencmd get_throttled
throttled=0x20000
[root@motionEye-Cam1 ~]#

but it still runs (already 5 minutes now)

**Comment by orcadiver** [comment] 2022-02-02 14:42
...means undervoltage? ...with an original power supply with 5.1V and 2.5A?

**Comment by starbasessd** [comment] 2022-02-02 14:48
Yes, it can. What camera? USB or CSI? 
USB draw can be too much. CSI Camera can be defective. Power Supply can be defective. 
Try different Power Supply. If using an extender cable for power, take it out of the equation.

**Comment by orcadiver** [comment] 2022-02-02 14:51
CSI Raspi v2 (8M)

**Comment by starbasessd** [comment] 2022-02-02 14:52
https://rpi4cluster.com/scripts/undervoltage/ is a good script.
I have one I use:
nano /data/oops.py
- - - - -
#!/usr/bin/env python2

import subprocess

GET_THROTTLED_CMD = 'vcgencmd get_throttled'
MESSAGES = {
    0: 'Under-voltage!',
    1: 'ARM frequency capped!',
    2: 'Currently throttled!',
    3: 'Soft temperature limit active',
    16: 'Under-voltage has occurred since last reboot.',
    17: 'Throttling has occurred since last reboot.',
    18: 'ARM frequency capped has occurred since last reboot.',
    19: 'Soft temperature limit has occurred'
}

print("Checking for throttling issues since last reboot...")

throttled_output = subprocess.check_output(GET_THROTTLED_CMD, shell=True)
throttled_binary = bin(int(throttled_output.split('=')[1], 0))

warnings = 0
for position, message in MESSAGES.iteritems():
    # Check for the binary digits to be "on" for each warning message
    if len(throttled_binary) > position and throttled_binary[0 - position - 1] == '1':
        print(message)
        warnings += 1

if warnings == 0:
    print("Looking good!")
else:
    print("Houston, we may have a problem!")
- - - - -
Watches for both temp and volt, and when it caps.

**Comment by orcadiver** [comment] 2022-02-02 14:53
I have two identical combinations (raspi/camera/power supply) and with both the same effect.

**Comment by starbasessd** [comment] 2022-02-02 14:54
I don't know, but the CPU and its protections are having issues. 
Did you 'overclock' at all?

**Comment by orcadiver** [comment] 2022-02-02 14:56
no, everything works with the default parameters (except for the configuration by MotionOS)

**Comment by starbasessd** [comment] 2022-02-02 14:58
I don't know, but the CPU and its protections are having issues.

**Comment by orcadiver** [comment] 2022-02-02 15:01
According to various forum posts, cooling would not be necessary - I use the original Raspi/camera combo case (no heatsink fits in there).

**Comment by orcadiver** [comment] 2022-02-02 15:07
with streaming qualiti 100% (uprated from default) now nothing works anymore

**Comment by starbasessd** [comment] 2022-02-02 15:08
It's not heat throttling. You can also check the messages log to see where the temps are...

**Comment by orcadiver** [comment] 2022-02-02 15:15
The backside of the board has about 50°C at the position of the CPU.

**Comment by starbasessd** [comment] 2022-02-02 15:20
vcgencmd measure_temp
or check the messaged log (Settings, Expert Settings)

**Comment by orcadiver** [comment] 2022-02-02 15:35
[root@motionEye-Cam1 ~]# vcgencmd measure_temp
temp=77.9'C
[root@motionEye-Cam1 ~]#

**Comment by orcadiver** [comment] 2022-02-02 15:35
already borderline - or?

**Comment by jawsper** [comment] 2022-02-02 15:36
That is quite hot, mine is at 61.2 degrees with no active cooling or heatsink. I did leave the top off of the case because it feels like it runs a bit hotter than the Pi Zero (1) W.

**Comment by starbasessd** [comment] 2022-02-02 15:36
Beyond 'borderline'.

**Comment by orcadiver** [comment] 2022-02-02 15:37
Feb  2 16:27:17 motionEye-Cam1 user.notice throttlewatch: currently: arm-frequency-capped , temperature: 80 C
Feb  2 16:28:17 motionEye-Cam1 user.notice throttlewatch: currently: arm-frequency-capped , temperature: 80 C

**Comment by starbasessd** [comment] 2022-02-02 15:38
Most Pis start throttling at 60-65. Most will shut down at 85.

**Comment by starbasessd** [comment] 2022-02-02 15:39
Interesting that vcgencmd get_throttled doesn't indicate the heat issue. Maybe a change they made...

**Comment by orcadiver** [comment] 2022-02-02 15:40
then the good one without cooling is actually not suitable for this scenario - I wonder why raspi then markets such things

**Comment by starbasessd** [comment] 2022-02-02 15:41
They are marketed as educational tools. People take it and use it for other things.

**Comment by orcadiver** [comment] 2022-02-02 15:41
then the Raspi Zero 2W needs at least a heat sink!

**Comment by starbasessd** [comment] 2022-02-02 15:41
As my favorite YTer says: WATER COOLED!

**Comment by orcadiver** [comment] 2022-02-02 15:43
I can't quite agree with that - my config is more or less meant like this: Raspi Zero 2W with camera v2.1 and Raspi combi case

**Comment by orcadiver** [comment] 2022-02-02 15:46
![grafik](https://user-images.githubusercontent.com/98274833/152187455-69e6644e-5be3-49bf-bf6c-cea3948f4e77.png)

**Comment by orcadiver** [comment] 2022-02-02 15:46
that does not serve its purpose then

**Comment by starbasessd** [comment] 2022-02-02 15:46
Go to RaspberryPi.org

**Comment by starbasessd** [comment] 2022-02-02 15:48
There were MAJOR issues with the Pi4Bs at the beginning with overheat, especially. They re-wrote a lot of firmware to lower the temps, and everyone came out with cooling solutions...

**Comment by starbasessd** [comment] 2022-02-02 15:49
Closing issue. Root Cause is heat.

**Closed as completed by starbasessd** 2022-02-02 15:49 UTC
Labels: question, troubleshooting, hardware issue
