### ISSUE TITLE
Motioneye not starting ubuntu 18.04

### ISSUE THREAD

**Issue by wolfi74** [ccrisan/motioneyeos#1508] opened 2018-05-04 07:38 UTC
Hi,
since update to ubuntu 18.04 motioneye wont start working.
The service is not started.
Please help.
Thanks

**Comment by chrisspen** [comment] 2018-05-12 17:25
What do the logs say? What error message do you get if you try to start it manually. No one can help you with an error report that simply says "Motioneye not starting".

**Comment by wolfi74** [comment] 2018-05-28 11:54
@abscode0 thank you very much. Works for me too

**Comment by jasaw** [comment] 2018-06-06 13:53
Looks like problem has been resolved. Closing issue.

**Closed by jasaw** 2018-06-06 13:53 UTC
Labels: motioneye

**Comment by wandering213** [comment] 2018-06-20 22:12
This issue is caused by old cache information left over from the old version of 
Ubuntu. Run rm -rf ~/.cache/pip and reinstall pycurl. 

https://stackoverflow.com/questions/50683895/importing-pycurl-with-libcurl4-raises-importerror
