### ISSUE TITLE
Feature request: preserve media until certain DISK CAPACITY is reached 

### ISSUE THREAD

**Issue by lukasig** [ccrisan/motioneyeos#2213] opened 2019-11-28 13:09 UTC
Hi

   Currently there is an option of preserving media for a certain amount of time (one day, week, month...).
   Is there any possibility of adding a feature that will create an option of preserving media until a certain disk capacity is reached?
   Car dash cams use this feature - when disk is full the oldest file gets deleted to make room for a new one.

 This would be very helpful in setting up a Google Drive or other cloud sync. We could select for example "preserve media up to 15GB", so when the older files get deleted locally they will be deleted form gdrive too, therefore always having the most recent 15GB of recordings available automatically.

Thank you

**Comment by jasaw** [comment] 2019-12-17 02:39
Duplicate of https://github.com/ccrisan/motioneyeos/issues/785

**Closed as completed by jasaw** 2019-12-17 02:39 UTC
Labels: duplicate
