### ISSUE TITLE
RPi 3 + motionEye = slow preview/recording fps

### ISSUE THREAD

**Issue by perrychan** [ccrisan/motioneyeos#227] opened 2016-03-22 18:16 UTC
First of all, great job with motionEyeOS. Was excited to see this software available and bought a couple of RPi 3s.

Unfortunately, recording stutters (1-2fps) once motion is detected. This applies whether its on large or small resolution. While watching the stream, I get 10fps, but drops down to 2-3fps as soon as it detects motion.

A lot of you don't seem to be having this problem. I am using an RPi camera when I first purchased my Raspberry Pi Model B. Think it might have anything to do with that?

**Comment by ccrisan** [comment] 2016-03-22 19:29
What fps setting have you configured? If  you're using a relatively high fps, the video encoding process might be too much for the CPU.

**Comment by perrychan** [comment] 2016-03-22 22:18
It was set to ~20fps. I have adjusted to 10fps and res to 640x480. Am getting an average framerate of 2.5 now, which is an improvement from ~1.5. It's an improvement, but it's not usable at the moment. Any ideas?

I tried to use Fast Network Camera, but the stream never appears (constant spinner).

**Comment by ccrisan** [comment] 2016-03-23 06:57
Please attach all of your log files. I'll take a look over them and see if I can spot anything fishy.

**Comment by perrychan** [comment] 2016-03-24 06:31
Attached are my logs.

[motionEyeOS-logs.zip](https://github.com/ccrisan/motioneyeos/files/187343/motionEyeOS-logs.zip)

**Comment by cuddylier** [comment] 2016-03-24 19:28
I just got a RPI 3 today as well and when it starts recording, my FPS also plummets
 even at 640 x 480 as well.

I've attached my logs.
[logs.zip](https://github.com/ccrisan/motioneyeos/files/188532/logs.zip)

**Comment by cuddylier** [comment] 2016-03-24 21:04
It appears to be any sort of recording, even with still images it starts to lag horribly and the FPS drops to 1 or 2 as @perrychan experienced.

**Comment by cuddylier** [comment] 2016-03-25 00:35
I watched the CPU usage during recording/image taking and it remains at a normal level of 30 - 40% and the I/O remains at 0% so it doesn't seem like the CPU isn't powerful enough at least?

**Comment by linuscool2** [comment] 2016-03-27 20:42
Have the same problem as @perrychan! 
Running RPi2

https://github.com/ccrisan/motioneyeos/issues/235

**Comment by ccrisan** [comment] 2016-03-28 06:50
I'll take a look over this. I haven't yet managed to investigate the problem.

**Comment by linuscool2** [comment] 2016-03-28 17:23
I will try the Motion software on Rasbian tonight to see if it's the MotionEyeOS or Motion that causes this problem. Will be back with the results

**Comment by CrazyEyesPete** [comment] 2016-04-01 21:26
Having same issue with RPI3 as well. I'm new to MotionEyeOS so maybe I'm something wrong.  When a person walks into the view, it is initially smooth video, but then looses several frames.

**Comment by cuddylier** [comment] 2016-04-01 21:28
@CrazyEyesPete Exactly the same thing I get, it's perfectly smooth for a few seconds when something moves and then drops frames as well. It still does this even with motion disabled and continuous recording enabled, it drops the frames permanently in this mode of course.

**Comment by zettam** [comment] 2016-04-03 08:08
Anyone able to find a temp solution to this, till this is fixed permanently?
I like motioneyeos but this makes it unusable :(

**Comment by perrychan** [comment] 2016-04-06 01:09
I'm hoping @ccrisan will be able to look over the logs soon.

**Comment by ccrisan** [comment] 2016-04-06 07:23
I will be taking care of this issue in the following weeks. I'm currently terribly busy with some personal matters but I haven't abandoned this project :)

**Comment by ShacharWeis** [comment] 2016-04-09 02:16
Same problem here, only much works. FPS drops to 0.1 once motion is detected. System is unusable.

**Comment by ccrisan** [comment] 2016-04-09 11:24
@perrychan , @ShacharWeis , @CrazyEyesPete , @zettam can I have your config files please? I cannot seem to reproduce the problem at all.

**Comment by zettam** [comment] 2016-04-09 13:03
I deleted everything, was waiting for the fix. Sorry.

**Comment by ShacharWeis** [comment] 2016-04-09 13:30
I've deleted the system and am now installing Zoneminder. After 12 hours my dropbox folder was full of false triggers and blank images that say "unable to open video device". Motioneyeos has a lot of potential, but I don't have time to debug it.

**Comment by tsrgit** [comment] 2016-04-09 23:54
@ccrisan , which config files and/or logs do you need?  I am having the same issue with my RPi 3.  It can easily maintain frame rates over 10 fps, even while detecting motion, as long as it is only streaming.  As soon as I enable the saving of movies onto a Samba share on a network drive, the frame rate drops to around 1 fps when motion is detected.

**Comment by cuddylier** [comment] 2016-04-09 23:55
I'm happy to provide my config as well if you let me know where to find it.

**Comment by zettam** [comment] 2016-04-10 08:00
@ShacharWeis I would not bother with zoneminder. I've tried it. It does the same thing, motion does (of course depends on what you're looking for) with a much complicated and needy setup process. It's old.

**Comment by ShacharWeis** [comment] 2016-04-10 12:40
@zettam yeah, I found that out. Can't even get Zoneminder to run at all. I've given up and am now using an old android phone. Very sad. Do you have a good guide for setting up Motion?

**Comment by zettam** [comment] 2016-04-10 17:46
@ShacharWeis motion is very easy to set up actually, did you check the online docs?
I got zoneminder running, it's not worth the effort really. Motion is much better, with the same capabilities (and a newer/better interface) with much cleaner setup.

**Comment by perrychan** [comment] 2016-04-14 08:44
@cuddylier you can find the log files under the Expert Settings menu.

**Comment by cuddylier** [comment] 2016-04-14 20:14
@perrychan I already attached my log files earlier in this issue report, just found the config backup part under General.

@ccrisan my config files: 
[ConfigFiles.zip](https://github.com/ccrisan/motioneyeos/files/219890/ConfigFiles.zip)

**Comment by Neckbeard2016** [comment] 2016-04-15 06:50
Same problem, currently on a RPi 2 (Model B).

**Comment by linuscool2** [comment] 2016-04-15 17:40
Is this bug only on MotionEyeOS or can switch to Motion untill the bug is fixed?

**Comment by ccrisan** [comment] 2016-04-15 20:09
I haven't been able to establish what "the bug" is about. People complain about slow fps in general. I'll take a look over the log files but I doubt there's one single problem that covers everything users are complaining about here.

**Comment by linuscool2** [comment] 2016-04-17 11:19
@ccrisan I dont know if this has something to do with the bug but read [this thread.](https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=99096)

They talk about ARMv6 and ARMv7. I dont know, maybe this has something to do with it.

**Comment by linuscool2** [comment] 2016-04-20 15:08
Just installed the newest version (20160410). Seems to be working now... At least better than before.  When motion is detected the FPS drops down to ~20-22FPS.

**Comment by kingsquirrel152** [comment] 2016-04-24 15:32
I too am having the same issues. I don't see any spike in CPU load.

**Comment by Kayak83** [comment] 2016-05-11 00:56
How are you guys monitoring CPU useage? I'm running the OS image and I don't see a way of seeing the CPU temp or load. Do I need to run it in Raspbian for that functionality?

**Comment by dmarkscouk** [comment] 2016-05-12 18:41
I'm also having the same issue. I've uploaded some same video's here:
https://www.dropbox.com/s/k05uyybz5yq2nlk/stuttery.zip?dl=0

I get the same issue weather I'm running hi or low resolution, and 30 or 20 fps.
I get great video with Fast Network Camera enabled, but as I can't record this it does not help.

I'm running a Raspberry Pi 3, with the camera module 2.

Thanks, David.

**Comment by ccrisan** [comment] 2016-05-13 08:55
@dmarkscouk unfortunately I'm afraid that's the best you can get with motionEyeOS. No hardware/accelerated encoding/decoding is performed by the motion daemon and therefore the performance is limited to what the CPU can offer.

A slow SD card may impact the performance as well, while saving videos to a network share could make matters even worse.

The reason why FNA is that fast is that it doesn't use the motion "backend" but rather makes use of the streamEye project to simply capture and stream the mjpeg frames without processing them in any way (hence the great performance).

I know this is not ideal and is probably not what most of you were hoping for when decided to try motionEye(OS) but this is what we have. 

I use 7 FNA-enabled cameras based on RPI1 and a powerful central computer with 8 cores running Arch Linux + motionEye that acts as a DVR for the RPI1 cameras. I believe this is the best setup you can have with motionEye.

**Comment by Phesten** [comment] 2016-05-14 01:47
So would it not be a good idea to use a RPi 3 as a hub for 3x Foscam IP cameras? They are capable of 720p video.

I intend to offload the camera data from the Pi to a USB attached hard drive.

I really want to be able to use MotionEyeOS for this, but it won't recognize the Foscams for some reason.

Sent from my iPhone

On May 13, 2016, at 1:55 AM, Calin Crisan <notifications@github.com<mailto:notifications@github.com>> wrote:


@dmarkscouk<https://github.com/dmarkscouk> unfortunately I'm afraid that's the best you can get with motionEyeOS. No hardware/accelerated encoding/decoding is performed by the motion daemon and therefore the performance is limited to what the CPU can offer.

A slow SD card may impact the performance as well, while saving videos to a network share could make matters even worse.

The reason why FNA is that fast is that it doesn't use the motion "backend" but rather makes use of the streamEye project to simply capture and stream the mjpeg frames without processing them in any way (hence the great performance).

I know this is not ideal and is probably not what most of you were hoping for when decided to try motionEye(OS) but this is what we have.

I use 7 FNA-enabled cameras based on RPI1 and a powerful central computer with 8 cores running Arch Linux + motionEye that acts as a DVR for the RPI1 cameras. I believe this is the best setup you can have with motionEye.

**Comment by tsrgit** [comment] 2016-05-17 18:48
@ccrisan are you saying that MotionEyeOS cannot achieve better than 1 fps on a RPi when recording video with the motion engine?

**Comment by ccrisan** [comment] 2016-05-18 18:15
It can, but at lower resolutions. I remember recording 3-4 fps videos at 640x480 with RPi1.

**Comment by cuddylier** [comment] 2016-05-18 18:17
That sucks then, not really usable :(

**Comment by ccrisan** [comment] 2016-05-18 18:19
@cuddylier I totally agree. That's why I recommend using RPi1 devices just as fast network cameras. I myself have 8 of them (I just finished installing the 8th one today), all of them working in FNA mode. I use an Odroid XU4 running motionEye as a hub that performs all the motion detection, movie encoding, notifications and whatnot.

**Comment by kingsquirrel152** [comment] 2016-05-18 18:20
So - I've had some success setting the motion trigger to a low setting (it
almost seems like if the motion trigger stops - it stops recoding the
video). Ill export settings and examples later tonight.

**Comment by dmarkscouk** [comment] 2016-05-19 09:08
Would it be possible to activate video recording using a physical motion sensor or ultrasonic distance sensor (I presume this would save CPU power, that could then be used to record video)? Recording video in HD is no problem when I use the standard raspivid function.

**Comment by MMiknis** [comment] 2016-05-25 19:11
It seems to be odd, using Pi2 I can stream at 20fps once motion is detected and recording starts it drops to 0.8fps. When I check the video the first two seconds are at high frame-rate but after that fps drops :( so recorded video is no good.

**Comment by hacker112** [comment] 2016-05-28 09:54
I think motion performance could be improved by:

* Using H.264 video encoding hardware acceleration (that I think the raspberry pi has, but it is not used by motion now)

and/or

* Using threads/parallel programming, so that motion can use more that one core. The raspberry pi 3 has four cores, and one is used by motion today. I am thinking have a separate thread for video encoding and one for motion detection.

What do you think about that, @ccrisan?

**Comment by ccrisan** [comment] 2016-05-28 19:26
I totally agree that motion could make use of the GPU-accelerated routines to encode h264 movies. I believe I saw some work in this direction, although I believe it was something related to ffmpeg and not motion itself. However, I am not willing to touch motion's source code so we'll need to use the motion version that we currently have.

There are ways to use an external ffmpeg command using the *extpipe* motion option but things start to get complicated and I don't have the time to add that to the current UI and then deal with all the problems that will occur.

**Comment by ikarisan** [comment] 2016-06-17 19:31
Very disappointing. :(

I had the choice between one of these Chinese "phone home" IP cameras and the Pi3+Motion solution and I did chose the last option. :/

Now I am stuck at 352x288 videos with 10fps instead of 1280x720/30fps as offered by these chinese IP cameras. :(

**Comment by ShadowNetworks** [comment] 2016-10-05 19:04
I'm okay with setting up MotionEye on a Linux machine and catching the FNA stream. Is there any way to secure the stream? Maybe my searches didn't turn up anything.

**Comment by Maxmudjon** [comment] 2016-12-01 20:12
I have a question . I'm on raspberry PI 3 connect IP camera and watch the video broadcast but slow. You do not know the problem?

**Comment by sjabbie88** [comment] 2016-12-26 19:23
> @ccrisan That's why I recommend using RPi1 devices just as fast network cameras. I myself have 8 of them (I just finished installing the 8th one today), all of them working in FNA mode. I use an Odroid XU4 running motionEye as a hub that performs all the motion detection, movie encoding, notifications and whatnot.

> Casin, can you clarify how you have set-up motionEye on your Odroid XU4 to perform the motion detection and encoding of your 8 cameras while they are set-up as Fast Network Cameras on the Odroid XU4? 

If I imitate your setup, I only have a fraction of the FNA camera options on the MotionEye Hub device, only general settings and no motion detection or encoding options....? 

The way I read it, It is a very interesting set-up =)

**Comment by ccrisan** [comment] 2016-12-26 19:58
FNC is not available on Odroid XU4. You'll have to enable it on your RPi-based cameras, and then add them as regular network cameras to the Odroid XU4 running regular motionEye or motionEyeOS.

**Comment by cuddylier** [comment] 2016-12-26 20:01
@ccrisan You haven't seen any FPS issues using motioneyeos on your Odroid in this setup during recording of video?

**Comment by ccrisan** [comment] 2016-12-26 20:32
I run my 9 cameras at 1024x768@10fps. Provided not all of them record motion at once, things are pretty smooth.

**Comment by cuddylier** [comment] 2016-12-26 20:34
Ah, still not great then :( Not worth investing in such a system for achieving that for me sadly.

**Comment by smanschi** [comment] 2016-12-30 13:58
Since v3.1, ffmpeg offers built-in support for using the decoding/encoding capabilities of the Raspberry Pi (see for example here [http://www.cnx-software.com/2016/06/29/ffmpeg-3-1-adds-support-for-openmax-encoding-on-raspberry-pi-va-api-h-264-h-265-encoding-and-more/](url)). I am not familiar with motion or ffmpeg.. would it be possible to make use of that? E.g., ship motioneyeos with a newer version of ffmpeg and activate the hardware encoding via an option?

Here is a link with the options (At least I think they are the proper ones): [http://stackoverflow.com/questions/40175644/ffmpeg-hardware-acceleration-on-raspberry-pi](url)

**Comment by KyleKatarn31** [comment] 2016-12-30 15:24
Hello,

I'm running 3 IP Cam on RPi 1B.
Of course it's lagging a lot but i'd like to know what is the 0.3/0.0 fps that is displayed on the motioneyeOS web monitoring page ?

**Comment by ccrisan** [comment] 2016-12-30 20:28
Just hover it with the mouse and you'll see a tooltip with details. It's basically streaming/capture fps.

**Comment by BigPapoo** [comment] 2017-01-08 23:54
Disable "Motion optimization" in "Video streaming" tab.

**Comment by shinji2009** [comment] 2017-02-25 04:57
How are you guys monitoring CPU useage?

**Comment by cuddylier** [comment] 2017-02-25 13:26
Using 'top' in ssh.

**Comment by shinji2009** [comment] 2017-02-25 13:45
cuddylier wow thanks... so it is not when expert settings - Enable System Monitoring. there is some values displayed. first is temperature, last is some kind of a network speed, i don't know which and where though. but second is complete mistery, i was thinking it is cpu load, but wondering what units it is.

**Comment by ccrisan** [comment] 2017-02-25 13:49
@shinji2009 it's the sysload and it's read from /proc/loadavg: https://github.com/ccrisan/motioneyeos/blob/master/board/raspberrypi/motioneye-modules/boardctl.py#L34

It's non-dimensional and possible values range from 0 to infinity. For a normal functioning, you should expect values from 0 to the number of cores.

**Comment by shinji2009** [comment] 2017-02-25 14:00
@ccrisan wow thanks...
strange thing that i'm using rpi3 and never seen values more than 1.4. i did  something wrong with installation or motioneyeos can't use 4 cores?

**Comment by ccrisan** [comment] 2017-02-25 14:03
Unless you have more than one camera attached to your PI, it's very unlikely to see loads above e.g. 1.5. 1.5 can be seen as 100% of one core (the thread handling your camera) + 50% of another one (the rest of the processes that are usually less CPU intensive).

Adding a second camera will instruct motion to spawn a second thread to handle the new camera. As far as I know it can't leverage more than one CPU (read: more than one thread) per camera.

**Comment by shinji2009** [comment] 2017-02-25 14:45
@ccrisan thank you. and what about third value? what speed is it?

**Comment by ccrisan** [comment] 2017-02-25 15:00
The total (send + receive) network IO, in kilobytes per second.

**Comment by cuddylier** [comment] 2017-02-25 15:47
@shinji2009 I'm sorry for confusing you, I knew about the monitoring overlay load value but I always check with top directly in ssh to see exactly what's going on (what each process is using) and the actual % although the load figure represents this somewhat.

**Comment by shinji2009** [comment] 2017-02-25 15:55
@cuddylier it's ok i need to know this too) it's my first *nix expirience

@ccrisan thank you. it is almost №5 of roadmap

**Comment by bortek** [comment] 2017-03-01 15:00
Guys if you are satisfied with the resolution please close the Issue. Thanks!

**Closed** 2017-03-07 14:54 UTC
Labels: question

**Comment by DeastinY** [comment] 2017-05-26 18:46
Hey, maybe this could/should be added to the device overway ?
I was expecting it to work with smooth 30FPS / FHD as well - maybe something to 'warn' people about ?
Furthermore - is there hardware that is capable of doing what we expect short of a dedicated server ?

**Comment by Sja91** [comment] 2018-01-06 12:41
Agreed with @DeastinY, This would've been nice to know before spending several hours on it. It's a shame too, seems like a good project. But thanks for it anyways!

**Comment by jasaw** [comment] 2018-01-06 13:30
@Sja91 Hardware accelerated video encoding is now supported on version 20171008 version and above, just make sure you choose OMX version of the movie format, like H264/OMX.
The original Raspberry Pi 1 should be able to handle 30 fps at 800 x 600 resolution. Raspberry Pi 2 & 3 will be able to handle higher resolution.

**Comment by Sja91** [comment] 2018-01-06 13:50
@jasaw Well this sounds promising! I tried googling around for this but I can't find anything on it. Would you mind explaining more? I'm not recording if that matters, just looking to stream video. But getting 2 fps

**Comment by smanschi** [comment] 2018-01-06 14:59
I think the general problem is not that the raspberry is too slow, but the way videos are handled is extremly inefficient. Typical motion detection software works like this:

1. Demultiplex incoming camera stream (e.g., mp4 to h264)
2. Decode video stream (h264 to raw images)
3. Analyze raw images (Detect motion)
4. If motion is detected, encode raw images to video stream (raw images -> h264)
5. Multiplex video stream (h264 -> mp4)

The computationally expensive part is the encoding of the video, which in my opinion is completely unnecessary. Last year, I started prototyping my own motion detection software. Instead of encoding the video, I stored the incoming h264 frames in a ring buffer (2. from above). As soon as a motion was detected in step 3, I multiplexed the frames from the ring buffer to an mp4 video. By doing this, the encoding (4.) could be skipped completely.

There are two main disadvantages with my approach. First, no information can be added to the video, as only the incoming stream is stored (e.g., no frame can be drawn around a detected moving object). Second, my approach was only able to handle h264 streams (which was not a problem for me as my camera was a h264 stream). The major advantage is that this approach is super fast. I don't remember the exact numbers, but by bypassing the encoding of the video the raspberry pi 3 could easily handle at least two Full HD cameras @ 25 fps. So it is definitely possible to use the raspberry pi for motion detection at high resolutions (without having only 2 or 3 fps).

Unfortunately, I did not have a lot of time to continue with the project as I finished my PhD last year. Maybe I will pick it up again and put some prototype on github. Would be great if something like this could be integrated into motioneyeos.

**Comment by KyleKatarn31** [comment] 2018-01-06 17:20
Appart from selecting H264/OMX as active codec, is there anything to do to enable HW acceleration ?

**Comment by shinji2009** [comment] 2018-01-07 07:50
**smanschi** very interesting. hope you will succeed. about first disadvantage: any info can be added to video using subtitles. like SRT. it is basically a plain text format, low storage and cpu usage, easy to generate.

wow gpu. maybe its time to move back to motioeyos

**Comment by PhilipWhiteside** [comment] 2019-11-17 09:27
@smanschi Did you ever end up putting that code somewhere. What you've described appears to be the wonder cure for many of the performance issues of VMSs. It may be very beneficial to share this with the project in a new issue, even if so they can review and see what could be implemented, if you don't have time to contribute directly. 

Your mentioned disadvantages are only for troubleshooting, in which the longer process can be used, in normal operations you don't use the boxes.

**Comment by solucionesuno** [comment] 2019-11-25 12:57
i have the same problem, which is the solution?

**Comment by solucionesuno** [comment] 2019-11-25 13:03
Disable "Motion optimization" in "Video streaming" tab solve the problem

**Comment by nacifyas** [comment] 2022-06-27 19:02
Same issue here. I am using a RPI 4B 8Gb ram. Motion detection enabled. Using mp4 (both variants with and without OMX result into a 2fps video output). Managed to get a **whopping 9FPS** when selecting .AVI however, its compatibility is very hard.
And I am pretty confident it is not too much for the rpi, since its always under a CPU load of 10-30% and as for RAM around 6-10%
It feels like if Motioneye is not using all the hardware's potencial.
Any help to increase that fps when recording, would be really appreciated.

**Comment by starbasessd** [comment] 2022-06-27 19:25
I have motionEyeOS dev20201026 on a RPi4-4GB (and -8GB) on Gigabit Ethernet for testing.
I have 6 cameras, 3 d-Link 5020Ls, 2 WiFi (11g) and 1 Gigabit Ethernet, at 800x600 15FPS
2 Foscam, 1 WiFi (11ac) and 1 Gigabit Ethernet, at 1280x720 15FPS
1 Tiga (generic) USB WebCam at 1280x720 15FPS
On the Pi they are all set to Movie Passthrough. All are giving the 15FPS when recording. All are showing 9-15FPS viewing to other PCs and phone/tablets/whatever.
If you go higher resolution, you will run into frame rate issues.

**Comment by nacifyas** [comment] 2022-06-27 19:34
My setup one Raspberry Pi NoIR V2 camera attached to the RPI 4. And the motionEye software is installed on the same system.
My RPI is connected to 1Gigabit LAN through ethernet connection.

In addition, my resolution requirements are not that high. I've set is up for a 1600x1200 (which is below FHD) @14fps.

So I don't think I am asking for an extreme resolution at a crazy frame rate.

With this setup, sadly I only get 2fps

**Comment by starbasessd** [comment] 2022-06-27 19:44
@nacifyas you don't say whether you are running motionEye or motionEyeOS, (and which version) which can be found in the Settings, General section.
Have you tried lowering the resolution to 1280x720? Or even 800x600?

**Comment by nacifyas** [comment] 2022-06-27 20:02
Thank you for your response.

I am using motioneye software installed on raspbian buster. Following the official guide. Please let me know if you need me to  give you any other info.

I am not considering lowering the resolution, since I really need it, specially at 800x600 and below, is not ideal for me.

However, lowering the resolution to 800x600 did increase the frame rate to 13fps using the AVI format.

In regard to the mp4 (OMX) format, there was a little improvement, going to 5fps.

I would like to know if there is any possibility to get more framerate, but by letting motioneye make more use of the hardware resources, rather than cutting into files quality.
 no 
As I've mentioned before, the load on my rpi is low regardless of what motioneye is doing.

Thank you in advance.

**Comment by starbasessd** [comment] 2022-06-27 20:08
motionEyeOS is much better as it has been optimized for motion and motionEye functionality by stripping out everything else not needed, and the OMX takes advantage of the GPU for video processing.
motionEyeOS for Pi4 can be found here: https://github.com/motioneye-project/motioneyeos/releases/download/nightly-dev/motioneyeos-raspberrypi4-dev20201026.img.xz
As I don't know what else you are running in RPiOS Buster, I cannot make any other recommendations.

**Comment by nacifyas** [comment] 2022-06-27 20:18
The only reason why I decided not to use the OS version of motioneye is because I need to have Nginx installed (for reverse proxy, to securely access the web interface). 

I supposed the way you get it installed (whether via the OS version, the installed version or the docker option) does not matter in terms of performance.

In my Pi OS Buster, I am only running nginx reverse proxy, (alongside with some basic tools such us glances for monitoring, or some cron jobs).

Thank you for your assistance and time.

**Comment by starbasessd** [comment] 2022-06-27 20:56
The more layers and other apps you add, the less performance you get. For some use cases, a Pi4 is not enough, and give you what you want. If you were to split the nginx to another machine, and run motionEyeOS on the Pi, I'd bet you'd gat the framerates you want at the resolutions you want.

**Comment by nacifyas** [comment] 2022-06-27 21:06
I see. Though that would be really nice.
Unfortunately I don't have another machine to which I can move my reverse proxy. However I will give it a try (I do have spare SD cards) and I will let you know on how it worked. (BTW I forgot to mention that in my setup, I use really high quality and fast SD card, I use the SanDisk Extreme Pro 64Gb, it is quite fast)

If it ends up being so resourceful as it seems, I'll keep it in mind until I can get an independent machine for nginx.

Thank you a lot for your time.

**Comment by nacifyas** [comment] 2022-06-29 21:26
I would like to share my progress with you on how I tuned my set up for now.

I've managed to keep up with a decently high resolution of 1920x1440 since it is 4/3 format you may also get a wider angle. And the best framerate I've managed to get was 15 fps in .avi format, which at least for my use case, at that resolution, it is pretty decent.

I am still using the installed version rather than the OS version of motioneye (I really want to test the OS variant it is just I have no time left to the deadline for this project). One face of the coin for using AVI is that it is easier to write. Please, correct me if I am wrong, but unless in my tests, .avi format was the most efficient and it seems to consume less resources to reproduce. Therefore, the output framerate even at such high resolution is barely compromised, considering that I have motion detection enabled (hence it is reason the avi movie is created). The other face of the coin however, is how lacking in terms of compatibility this format is, compared to mp4. In addition, it is not lightweight, so the sd card may run out of space quickly.

To mitigate the mentioned issues, I have set up two Motion End Commands. One proceeds converting the recently generated .avi video file to mp4 using the `ffmpeg` command, so now watching the recordings is much easier. The other one, uses `rsync` to synchronize the motioneye storage directory with Nextcloud folder, using webdav mounted through `davfs2`, therefore storage is no longer a problem. I have plenty of it for my needs on my instance.

I had tried specifying the storage folder with the imported nextcloud folder, which came up with a ton of benefits, but the network delays compromised drastically the performance.

For now I've found the sweet spot in my setup and I am pretty happy with it. Thank you a lot for the MotionEye project, and for your time.
