### ISSUE TITLE
Feature request, Moving arround on MotionEye cameras

### ISSUE THREAD

**Issue by SuneBielefeldt** [ccrisan/motioneyeos#1389] opened 2018-02-19 11:28 UTC
Is there any way to move around the order of the configured cameras without having to reinstall them all from the beginning ?

![image](https://user-images.githubusercontent.com/9556987/36380934-502a7f14-1584-11e8-906c-aefedfcfa328.png)

**Comment by ccrisan** [comment] 2018-02-22 13:31
Duplicate of https://github.com/ccrisan/motioneyeos/issues/1202.

**Closed by ccrisan** 2018-02-22 13:31 UTC
